# Generated by Django 2.2.10 on 2020-02-06 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_atcconnection_member_pilotconnection'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilotconnection',
            name='destination',
            field=models.CharField(default='-', max_length=4),
        ),
        migrations.AddField(
            model_name='pilotconnection',
            name='origin',
            field=models.CharField(default='-', max_length=4),
        ),
    ]
