# Generated by Django 2.2.10 on 2020-02-08 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atcconnection',
            old_name='rating',
            new_name='frequency',
        ),
        migrations.RemoveField(
            model_name='atcconnection',
            name='callsign',
        ),
        migrations.RemoveField(
            model_name='atcconnection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='atcconnection',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pilotconnection',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='pilotconnection',
            name='callsign',
        ),
        migrations.RemoveField(
            model_name='pilotconnection',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pilotconnection',
            name='name',
        ),
        migrations.AddField(
            model_name='atcconnection',
            name='member_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='callsign',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pilotconnection',
            name='member_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Member'),
            preserve_default=False,
        ),
    ]
