# Generated by Django 2.2.10 on 2020-02-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200209_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcconnection',
            name='frequency',
            field=models.FloatField(),
        ),
    ]
