# Generated by Django 2.2.10 on 2020-02-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200209_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atcconnection',
            name='frequency',
            field=models.IntegerField(null=True),
        ),
    ]
