# Generated by Django 2.2.10 on 2020-02-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200209_0232'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('member_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.Member')),
                ('position', models.CharField(default='-', max_length=42)),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('blog.member',),
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='event',
            name='author',
        ),
        migrations.RemoveField(
            model_name='event',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.IntegerField(default=None, primary_key=True, serialize=False),
        ),
    ]
