# Generated by Django 2.2.10 on 2020-02-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200209_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='banner',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
